version: '3.8'
services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5678:5432'

volumes:
  postgres:
